import React, { useEffect } from 'react';
import { View, Text, StyleSheet, Platform } from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
  withDelay,
  withSequence,
  withRepeat,
  Easing,
  interpolate,
} from 'react-native-reanimated';
import Svg, { Path } from 'react-native-svg';
import { SPACING } from '../constants/theme';

interface LogoProps {
  size?: 'small' | 'medium' | 'large';
  animated?: boolean;
  showTagline?: boolean;
  pulsating?: boolean;
}

/**
 * Tefillah breathing logo — pixel-identical to:
 *   - the web app's <Logo /> in tefillah-web/src/components/Logo.tsx
 *   - the app icon generated by frontend/scripts/generate-app-icons.py
 *
 * Three live layers, each on its own breath timeline:
 *   1. Outer dim-olive disc      (slow scale + opacity pulse — "luminates")
 *   2. Inner brighter olive disc (gentler opacity pulse)
 *   3. Solid gold Ionicons flame (scale-breath only). The flame body and
 *      its inner droplet are drawn as two separate <Path>s with explicit
 *      colours, so the droplet always reads as dark olive — never the
 *      transparent hole the default Ionicons glyph would punch through.
 *
 * Colours are hard-coded (NOT from theme tokens) so the identity is consistent
 * across light + dark UI and matches the launcher icon exactly.
 */

const COLOR_DISC_OUTER = '#3a2f15';
const COLOR_DISC_INNER = '#5d4a1a';
const COLOR_FLAME_GOLD = '#d4af37';
const COLOR_FLAME_DROP = '#1a1408';

// Ionicons "flame" outer body — viewBox 0 0 512 512.
const FLAME_BODY_D =
  'M394.23,197.56a300.43,300.43,0,0,0-53.37-90' +
  'C301.2,61.65,249.05,32,208,32a16,16,0,0,0-15.48,20' +
  'c13.87,53-14.88,97.07-45.31,143.72' +
  'C122,234.36,96,274.27,96,320' +
  'c0,88.22,71.78,160,160,160s160-71.78,160-160' +
  'C416,276.7,408.68,235.51,394.23,197.56Z';

// Ionicons "flame" inner droplet — drawn on top so it reads as solid olive.
const FLAME_DROP_D =
  'M288.33,418.69C278,429.69,265.05,432,256,432' +
  's-22-2.31-32.33-13.31S208,390.24,208,368' +
  'c0-25.14,8.82-44.28,17.34-62.78,4.95-10.74,10-21.67,13-33.37' +
  'a8,8,0,0,1,12.49-4.51' +
  'A126.48,126.48,0,0,1,275,292' +
  'c18.17,24,29,52.42,29,76C304,390.24,298.58,407.77,288.33,418.69Z';

interface SizeConfig {
  outer: number;   // outer olive disc diameter in px
  inner: number;   // inner olive disc diameter in px
  flame: number;   // flame SVG box (square) in px
  text: number;    // wordmark font size
  tagline: number; // tagline font size
}

const SIZE_CONFIG: Record<NonNullable<LogoProps['size']>, SizeConfig> = {
  small:  { outer: 60,  inner: 44,  flame: 28, text: 18, tagline: 10 },
  medium: { outer: 96,  inner: 70,  flame: 44, text: 28, tagline: 12 },
  large:  { outer: 144, inner: 104, flame: 64, text: 40, tagline: 14 },
};

export const Logo: React.FC<LogoProps> = ({
  size = 'medium',
  animated = false,
  showTagline = false,
  pulsating = true,
}) => {
  const cfg = SIZE_CONFIG[size];

  // Entry animation (used on splash + landing).
  const entryOpacity = useSharedValue(animated ? 0 : 1);
  const entryScale = useSharedValue(animated ? 0.85 : 1);

  // Three independent breath timelines, mirroring the web @keyframes.
  const ring = useSharedValue(0);
  const glow = useSharedValue(0);
  const icon = useSharedValue(0);

  useEffect(() => {
    if (animated) {
      entryOpacity.value = withDelay(
        200,
        withTiming(1, { duration: 800, easing: Easing.out(Easing.cubic) }),
      );
      entryScale.value = withDelay(
        200,
        withTiming(1, { duration: 800, easing: Easing.out(Easing.back(1.2)) }),
      );
    }

    if (pulsating) {
      // Outer disc — slowest (5s), biggest movement.
      ring.value = withRepeat(
        withSequence(
          withTiming(1, { duration: 2500, easing: Easing.inOut(Easing.ease) }),
          withTiming(0, { duration: 2500, easing: Easing.inOut(Easing.ease) }),
        ),
        -1,
        false,
      );
      // Inner disc — 4s.
      glow.value = withRepeat(
        withSequence(
          withTiming(1, { duration: 2000, easing: Easing.inOut(Easing.ease) }),
          withTiming(0, { duration: 2000, easing: Easing.inOut(Easing.ease) }),
        ),
        -1,
        false,
      );
      // Flame — 4s subtle scale breath.
      icon.value = withRepeat(
        withSequence(
          withTiming(1, { duration: 2000, easing: Easing.inOut(Easing.ease) }),
          withTiming(0, { duration: 2000, easing: Easing.inOut(Easing.ease) }),
        ),
        -1,
        false,
      );
    }
  }, [animated, pulsating]);

  const containerStyle = useAnimatedStyle(() => ({
    opacity: entryOpacity.value,
    transform: [{ scale: entryScale.value }],
  }));

  const outerDiscStyle = useAnimatedStyle(() => ({
    opacity: interpolate(ring.value, [0, 1], [0.62, 1]),
    transform: [{ scale: interpolate(ring.value, [0, 1], [0.95, 1.05]) }],
  }));

  const innerDiscStyle = useAnimatedStyle(() => ({
    opacity: interpolate(glow.value, [0, 1], [0.78, 1]),
    transform: [{ scale: interpolate(glow.value, [0, 1], [0.97, 1.02]) }],
  }));

  const flameStyle = useAnimatedStyle(() => ({
    transform: [{ scale: interpolate(icon.value, [0, 1], [0.97, 1.03]) }],
  }));

  return (
    <Animated.View style={[styles.container, containerStyle]}>
      <View
        style={[
          styles.badge,
          { width: cfg.outer, height: cfg.outer, borderRadius: cfg.outer / 2 },
        ]}
      >
        {/* Layer 1 — outer dim-olive disc (slow pulse) */}
        <Animated.View
          style={[
            styles.absoluteCentre,
            outerDiscStyle,
            {
              width: cfg.outer,
              height: cfg.outer,
              borderRadius: cfg.outer / 2,
              backgroundColor: COLOR_DISC_OUTER,
            },
          ]}
        />
        {/* Layer 2 — inner brighter olive disc */}
        <Animated.View
          style={[
            styles.absoluteCentre,
            innerDiscStyle,
            {
              width: cfg.inner,
              height: cfg.inner,
              borderRadius: cfg.inner / 2,
              backgroundColor: COLOR_DISC_INNER,
            },
          ]}
        />
        {/* Layer 3 — Ionicons flame, body + droplet drawn explicitly */}
        <Animated.View style={[styles.absoluteCentre, flameStyle]}>
          <Svg width={cfg.flame} height={cfg.flame} viewBox="0 0 512 512">
            <Path d={FLAME_BODY_D} fill={COLOR_FLAME_GOLD} />
            <Path d={FLAME_DROP_D} fill={COLOR_FLAME_DROP} />
          </Svg>
        </Animated.View>
      </View>

      <View style={styles.textContainer}>
        <Text style={[styles.title, { fontSize: cfg.text, color: '#fefefe' }]}>
          Tefillah
        </Text>
        {showTagline && (
          <View style={styles.taglineRow}>
            <View style={styles.taglineLine} />
            <Text style={[styles.tagline, { fontSize: cfg.tagline, color: '#a0a0b0' }]}>
              Connecting World Through Prayer
            </Text>
            <View style={styles.taglineLine} />
          </View>
        )}
      </View>
    </Animated.View>
  );
};

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
  },
  badge: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.sm,
  },
  absoluteCentre: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textContainer: {
    alignItems: 'center',
  },
  title: {
    fontWeight: '200',
    letterSpacing: 6,
    fontFamily: Platform.OS === 'ios' ? 'Didot' : 'serif',
  },
  taglineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  taglineLine: {
    width: 26,
    height: 1,
    backgroundColor: '#8b7a4d',
    opacity: 0.7,
    marginHorizontal: SPACING.sm,
  },
  tagline: {
    fontWeight: '300',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    fontFamily: Platform.OS === 'ios' ? 'Avenir-Light' : 'sans-serif',
  },
});
